// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: campaigns.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const getCandidateAd = `-- name: GetCandidateAd :many

SELECT 
  c.campaign_id,
  c.min_age,
  c.max_age,
  c.country,
  c.bid_cpm,
  t.placement_ids,
  t.interests_any,
  t.devices_any,
  t.languages_any,
  t.creators_any,
  cr.creative_id,
  cr.asset_url,
  cr.click_url
FROM campaigns c
JOIN campaign_targeting t ON c.campaign_id = t.campaign_id
JOIN creatives cr ON c.campaign_id = cr.campaign_id
WHERE c.status = 'active'
  AND c.country = $1
  AND $2 BETWEEN c.min_age AND c.max_age
  AND (cardinality(t.placement_ids) = 0 OR $3::text = ANY(t.placement_ids))
  AND (cardinality(t.devices_any)   = 0 OR $4::text = ANY(t.devices_any))
  AND (cardinality(t.languages_any) = 0 OR $5::text = ANY(t.languages_any))
  AND (cardinality(t.creators_any)  = 0 OR $6::text = ANY(t.creators_any))
  AND (cardinality(t.interests_any) = 0 OR t.interests_any && $7::text[])
`

type GetCandidateAdParams struct {
	Country     string
	Age         int32
	PlacementID string
	Device      string
	Language    string
	CreatorID   string
	Interests   []string
}

type GetCandidateAdRow struct {
	CampaignID   string
	MinAge       int32
	MaxAge       int32
	Country      string
	BidCpm       string
	PlacementIds []string
	InterestsAny []string
	DevicesAny   []string
	LanguagesAny []string
	CreatorsAny  []string
	CreativeID   string
	AssetUrl     string
	ClickUrl     string
}

func (q *Queries) GetCandidateAd(ctx context.Context, arg GetCandidateAdParams) ([]GetCandidateAdRow, error) {
	rows, err := q.db.QueryContext(ctx, getCandidateAd,
		arg.Country,
		arg.Age,
		arg.PlacementID,
		arg.Device,
		arg.Language,
		arg.CreatorID,
		pq.Array(arg.Interests),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateAdRow
	for rows.Next() {
		var i GetCandidateAdRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.MinAge,
			&i.MaxAge,
			&i.Country,
			&i.BidCpm,
			pq.Array(&i.PlacementIds),
			pq.Array(&i.InterestsAny),
			pq.Array(&i.DevicesAny),
			pq.Array(&i.LanguagesAny),
			pq.Array(&i.CreatorsAny),
			&i.CreativeID,
			&i.AssetUrl,
			&i.ClickUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
