// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Campaign struct {
	CampaignID string
	Name       string
	Status     string
	BidCpm     string
	MinAge     int32
	MaxAge     int32
	Country    string
}

type CampaignTargeting struct {
	CampaignID   string
	PlacementIds []string
	InterestsAny []string
	DevicesAny   []string
	LanguagesAny []string
	CreatorsAny  []string
}

type Creative struct {
	CreativeID string
	CampaignID string
	AssetUrl   string
	ClickUrl   string
	Format     string
}

type User struct {
	UserID    string
	Country   string
	Age       int32
	Device    string
	Language  string
	Interests []string
}
