// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const getUserById = `-- name: GetUserById :one

SELECT user_id, age, country, device, language, interests
FROM users
WHERE user_id = $1
`

type GetUserByIdRow struct {
	UserID    string
	Age       int32
	Country   string
	Device    string
	Language  string
	Interests []string
}

func (q *Queries) GetUserById(ctx context.Context, userID string) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, userID)
	var i GetUserByIdRow
	err := row.Scan(
		&i.UserID,
		&i.Age,
		&i.Country,
		&i.Device,
		&i.Language,
		pq.Array(&i.Interests),
	)
	return i, err
}
